### ISSUE TITLE
Create Read Activity

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#100]
reading position (json object)
save it to publication in database
make sure reading position is there when fetching a publication.

**Comment by Marie000** [comment]
@baldurbjarnason do you know what read activity would look like?

**Comment by baldurbjarnason** [comment]
That's something I've been thinking about for a while.

We know that the basic structure will be that of a `type: Read` activity that, like many others will have the document as its object and the publication as its context.

The biggest question is how do we indicate exact positions? The most obvious solution would be to use a property from the Open Annotation spec: [`oa:hasSelector`](https://www.w3.org/TR/annotation-vocab/#hasselector). (So we'd have to add `{ oa: 'http://www.w3.org/ns/oa#' }` to our context doc for the JSON-LD to stay valid.)

The value of `oa:hasSelector` would be a selector object.

So the whole would look something like:

```json
{
  "@context": [
          "https://www.w3.org/ns/activitystreams",
          { "reader": "https://rebus.foundation/ns/reader"}
        ],
  "summary": "Optional summary",
  "type": "Read",
  "actor": "http://example.org/profiles/joe",
  "object": "http://example.com/document/1",
  "context": "http://example.com/publication/1",
  "oa:hasSelector": {
      "type": "XPathSelector",
      "value": "/html/body/p[2]/table/tr[2]/td[3]/span"
    }
}
```

One question I've been thinking about lately is whether we should worry about keeping JSON-LD validity at this stage of development. Does it make sense for us to focus on first making the JSON files nicer to read and understand? I can always write a custom JSON-LD context model later on that makes the file format we've chosen valid.

If we decide not to worry about JSON-LD for now we could instead do

```json
{
  "@context": [
          "https://www.w3.org/ns/activitystreams",
          "https://json-ld.rebus.ink/"
        ],
  "summary": "Optional summary",
  "type": "Read",
  "actor": "http://example.org/profiles/joe",
  "object": "http://example.com/document/1",
  "context": "http://example.com/publication/1",
  "position": "/html/body/p[2]/table/tr[2]/td[3]/span"
}
```

Where `https://json-ld.rebus.ink/` is a placeholder URL where we would later host our custom `@context` JSON-LD file.

And we could do the same with all of our `reader:` prefixed properties: just pick the best un-prefixed name and then 'make it right' later on.

Does that make sense or am I just making things more complicated?

**Comment by Marie000** [comment]
I will have to take a closer look at the json-ld context thing. 

How would you want to get the read activity back? I assume it would be attached to a document. Do you want only the latest read activity? Or an array of all read activities?

**Comment by baldurbjarnason** [comment]
An array of all read activities would be very hard to manage as there could be quite a few of them.

Having only the latest read activity would definitely do the job of letting  us track the current position across platforms. 

I don't know if we want to do something more clever with read activities later down the line but "den tid, den sorg" as the Danish say. No sense in solving problems we don't have and might never have.

So, yeah. Let's start with the latest one for each document attached to that document.

It would also be very useful if the latest Read activity for a publication as a whole were attached to the publication JSON as well.

Are you thinking about adding it to the `attachment` array or do you think it should be in its own property?

**Comment by Marie000** [comment]
I was thinking of having it in its own property, but if you prefer to have it in the attachment, I can do that too.

**Comment by baldurbjarnason** [comment]
No a property is good. Having to filter the attachments would have been a hassle 🙂
