### ISSUE TITLE
make swagger documentation available without having to start the server

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#129]
Right now the swagger documentation is only available in  route on the server. 
We should make it available elsewhere. Maybe gh-pages?

**Comment by baldurbjarnason** [comment]
Yes! I've been thinking about the same problem for the front end style docs. GitHub pages makes sense. The only caveat is that the domain/address will probably change once this project has a proper name. But even so, IMO setting up GitHub pages for documentation (both here and on reader-frontend) is the right thing to do.
