### ISSUE TITLE
Look into open api + authentication issue

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#163]
Goal: come up with a plan

**Comment by baldurbjarnason** [comment]
When I last looked into this, one of the standards/tech that looked very promising was IndieAuth, which is a simplified Oauth profile which uses URLs as identifiers for external services and sets a few conventions that simplify the protocol:

- ["OAuth for the Open Web"](https://aaronparecki.com/2018/07/07/7/oauth-for-the-open-web) (by the author of the spec)
- ["IndieAuth"](https://www.w3.org/TR/indieauth/) (the W3C technical note)
- Specifically the use case we'd be looking into is this one: ["Obtaining An Access Token"](https://indieweb.org/obtaining-an-access-token) (The URL the user uses to sign in in the examples in that document is the primary service that the external service wants a token for; in the examples it's the URL of the user's blog and the use case is to authenticate external blog editing apps.)

One possibility to consider is to build a specific auth server (or auth express app) that combines the login code from the front end with an IndieAuth-style authorization/token endpoint.

Alternatively, if we want to keep things really really simple, we could have a User Settings page where the user can create and revoke long-lasting authentication tokens themselves (which is something that a few 'lower budget' services do, such as Pinboard).

Also, there's a good chance that Auth0 has some service or another specifically for this use case.

Just my 2c, and all that. I'm sure there are plenty of other possibilities 🙂

**Comment by baldurbjarnason** [comment]
I don't know if this is helpful or not (helped me) but micro.blog uses IndieAuth to manage authorization for external apps and services (i.e. external blog editors and the like) which is somewhat similar to how we're hoping to have some way to let users add external services that speak to the API.

And [micro.blog has a documentation page for developers explaining how indieauth works from a developer's perspective](http://help.micro.blog/2019/api-indieauth/) and how it would then look like from a user's perspective.

It definitely helped me make more sense of IndieAuth as an approach.
