### ISSUE TITLE
Figure out how to store metadata in the database

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#197]
Should user schema.org standard. 
Find a way to store it in a relational database.

**Comment by baldurbjarnason** [comment]
For reference (from our slack):

> Here's a link to the current Web Publication Manifest draft standard: https://w3c.github.io/wpub/
> 
> The simplest way to think about it is that they've taken the schema.org CreativeWork type (and subtypes) https://schema.org/CreativeWork added `resources` (which is a file manifest/attachments), `readingOrder`, and `links` which is a very useful list of external resources relevant to the publication.

(That's over-simplifying what the WPUB does but it's a starting point.)
