### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#198]

**Comment by baldurbjarnason** [comment]
Tough question. One use case that I can think of for editing links or resources is if the reader comes across a resource while reading that should be embedded or referenced properly by the publication. This could be tied in with future improvements in our footnote/link handling

The scenario would be something like:

> The Reader is reading through the book, comes across an interesting reference that is linked from the body of the text. Pressing on that opens the target resource/page in a popover (like footnote links do on some sites) with buttons that let you either save the external page as an Article in your library or add it as an embedded resource to the current publication. The latter would mean that the article would be automatically saved offline whenever the publication is saved offline.

Offering to save an external article to the library is something we can do with the current API with no problem. The question is whether offering the ability to add that resource to the current publication makes any sense?

Also worth asking whether we'll ever get around to implementing features like these 😁 

On the readingOrder, I think we can safely say that a publication with a new reading order should be an entirely new publication.

So the short answer would be a 'no' on changing readingOrder and a 'maybe' on links and resources?

**Comment by Marie000** [comment]
@rabhiso 
Once you are done with the documentation you can work on that. 
The goal is to allow changes to publications. Right now we allow updates to Notes only, so you can refer to that as an example.
We will allow changes to:
- name
- attribution fields (author, editor... eventually more)
- datePublished
- metadata fields (keywords, inLanguage... eventually more)
- description
- json (we only change the whole json object. Cannot change individual properties within json)

One complication is that some of the changes will be with attributions. You can always keep that for last, but basically it will work like this: if changes include an attribution field (for example 'author'), you would delete all 'author' attributions for this publication and replace them with new attributions. 

Another smaller complication is that some propreties (for now, keywords, inLanguage. But eventually there will be others) are store in the database under metadata, as part of a json object. Changing one should now change the whole metadata object. 

Let me know if you have any questions.
