### ISSUE TITLE
Cache library route

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#204]
enable "if updated since" feature.

**Comment by baldurbjarnason** [comment]
For reference:

- ["If-Modified-Since request HTTP header"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since)
- ["If-None-Match HTTP request header"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match)

Both work.

**Comment by Marie000** [comment]
Not sure if I am fully understanding how it works. In order for the if-modified-since header to work, I would need to compare it with the last-modified timestamp. So I would have to fetch the library and within the library look for updated timestamps for all publications and tags and find the latest one. Except that there might also be changes to the publication_tag table, which would not be reflected there.

**Comment by Marie000** [comment]
One option would be to use a Redis (or similar) database to store last-modified timestamps and other caching stuff. 

To be discussed later.
