### ISSUE TITLE
Should tag types accept any string?

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#306]
Right now, tags have a proprety 'type' equal to 'reader:Stack' (might be renamed reader:Collection). This is the only type that is accepted so far.

My suggestion would be that instead of creating other standard types for other tags, we could have them all have a type of 'reader:Tag', and have another property called tagType, which could be any string.

This is how we work with notes. They all have a type of 'Note' and the noteType can be anything. 

Doing it that way would mean more flexibility. There wouldn't need to be any implementation changes in the backend when we need a new type of tag, so less work for me :stuck_out_tongue: 

Thoughts @baldurbjarnason ?

**Comment by Marie000** [comment]
Note: delete tag already uses 'Tag' as the type. That is a mixup, but I will wait to see what we want to do with tags before fixing it.

**Comment by baldurbjarnason** [comment]
This works for me.
