### ISSUE TITLE
Should these throw errors?

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#308]
I am adding some tests for all sort of user errors. Some of them I don't know if they should throw or not. Gathering the questions here as I go:

- What if a string is passed to query parameters for pagination. e.g. GET user-{id}/library?limit=string&page=two 
Should it throw or use the default? (limit = 10 and page = 1) - No idea when that might happen... but users are funny sometimes. 
It could also try to parse the string first? 
Right now, it just skips pagination altogether if I pass a string and returns everything. Obviously not what we want. UPDATE: now it uses the default. I can change that if we need, but seemed better than skipping pagination. 

- When filtering the library by attribution with a role, if the role is invalid, right now it returns an empty library. Should it return an error instead?
e.g. GET user-{id}/library?author=smith&role=invalidRole

- What should happen if someone creates an object and includes invalid properties? Right now it just ignores those properties and doesn't throw any error. Is that what we want?

- Similarly, what should happen if someone updates an object with invalid properties? What about valid properties that cannot be updated?

**Comment by Marie000** [comment]
@baldurbjarnason some questions that arose I was reviewing my tests.

**Comment by baldurbjarnason** [comment]
- Going for the default when the query parameter makes no sense seems like a sound strategy to me
- Returning an empty library under those circumstances makes more sense from the front end perspective at the moment as you could think of it as being a search with no results.
- I think ignoring unknown/invalid properties makes sense for now. For example the front end (or another API client) might have been updated to work also with an upcoming version of the API where those properties are no longer invalid/unknown. We could revisit this if the API ever reaches the stage where we're confident in it not changing for a while.
- Same with updates.

 👍

**Comment by Marie000** [comment]
Nice. That is exactly what the API is doing right now.
