### ISSUE TITLE
Should creating a note need both inReplyTo and context?

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#310]
So now the inReplyTo is not a document id anymore, it is the url to the actual file. So that is the publicationUrl + relative path. 
Right now we also require that the object should have a context, which is the publication id.

I suggest we only ask for one or the other. If a note belongs to a document, we can have the publicaitonId from the inReplyTo url anyways. 

Any objections?
@baldurbjarnason

**Comment by baldurbjarnason** [comment]
No objections. It should make the API simpler and less weird to use which is always a plus. 👍

**Comment by Marie000** [comment]
If a note is created with both a inReplyTo (document url) and a context (publication id), should it throw an error or just quietly ignore the publication id?

**Comment by baldurbjarnason** [comment]
Quietly ignore, I think?
