### ISSUE TITLE
Fun bug with concurrent document uploads

### ISSUE THREAD

**Issue by baldurbjarnason** [RebusFoundation/reader-api#332]
Here's a fun bug I discovered and took me a while to figure out.

I've been mostly focusing on testing PDF uploads which has only two document uploads for each publication: the PDF itself and the cover image.

For some reasons the cover upload was always failing. It took me a while but it's happening because I had set the upload queue to upload up to three items at a time. Which lead to two uploads trying to create a Google Storage bucket for that publication both at the same time, which failed. 😁 

(This became way more obvious when I switched back to testing epubs where each publication has a bunch of files.)

Everything works again once I turned off concurrent uploads but obviously a lot slower 🙂

**Comment by Marie000** [comment]
That is using the publication-{id}/file-upload ?

**Comment by baldurbjarnason** [comment]
Yup.

**Comment by Marie000** [comment]
Ok, ideally I wanted to allow multiple file upload, like with /reader-{id)/file-upload. But I am not sure how to get the additional information (like path, etc) for multiple files. 
I will look at this again.

**Comment by Marie000** [comment]
If I were to make it accept multiple file uploads, I would need to somehow get the data for each file separately.
Something like: 
```
{ 
  'file1.txt': { path: '/path/to/file1.text', ... },
  'file2.txt': { path: '/another/path/file2.txt, ... }
}
```
which could be stringified json sent with the form data. 

The problem with that is that file names might not be unique.
When I receive the file, my file object looks like this:
```
{ fieldname: 'file',
  originalname: 'test-file1.txt',
  encoding: '7bit',
  mimetype: 'text/plain',
  buffer:
   <Buffer 73 6f 6d 65 20 63 6f 6e 74 65 6e 74 2e 0a 2e 2e 2e 2e 2e 0a 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e 2e ... 139 more bytes>,
  size: 189 }
```
So I would have no way to make a difference between the information for `/index.html` and `subfolder/index.html` if they are uploaded as part of the same request.

**Comment by baldurbjarnason** [comment]
Ah, I think we're talking about two different problems here.

1. Uploading more than one file per request, which is indeed probably more hassle than it's worth
2. The browser attempting to make two upload requests at the same time which the server is attempting to handle almost concurrently.

The bug I'm referring to here happens even when you do one file upload per request. 

When the browser sends two requests at the same time, the API server manages somehow to check for the existence of the bucket for that publication both at the same time. Both then try to create that bucket at the same time which causes the actual second request to fail.

**Comment by Marie000** [comment]
I thought that maybe allowing multiple uploads would magically fix the problem. But it is indeed causing more problems than it is solving.
I will get back to trying to solve the original problem.

**Comment by baldurbjarnason** [comment]
Ah, yeah. See what you mean. Yes indeed.

(Isn't concurrency fun 😁?)

**Comment by baldurbjarnason** [comment]
Could it be that the fix is causing issues? I'm getting the following error on file-uploads:

```
 TypeError: Cannot read property 'statusCode' of undefined
at Publication.byId.then (/srv/node_modules/hobb-api/routes/publication-file-upload.js:95:30)
```
I think that for some reason Google storage is causing an unrelated error, maybe even Google-specific?

For some reason all of a sudden rr-dev threw up a lot of errors so this may be caused by an entirely unrelated issue.
