### ISSUE TITLE
Notes create throwing errors: no document found

### ISSUE THREAD

**Issue by baldurbjarnason** [RebusFoundation/reader-api#337]
```
{ Error: note creation failed: no document found with url https://localhost:4430/publication-726d9842ec80bb127d60ea99049c45a6/OPS/c01.xhtml
    at handleCreate (/Users/baldurbjarnason/Projects/reader-frontend/node_modules/hobb-api/routes/activities/create.js:79:18)
  data:
   { type: 'Document',
     id:
      'https://localhost:4430/publication-726d9842ec80bb127d60ea99049c45a6/OPS/c01.xhtml',
     activity: 'Create Note' },
  isBoom: true,
  isServer: false,
  output:
   { statusCode: 404,
     payload:
      { statusCode: 404,
        error: 'Not Found',
        message:
         'note creation failed: no document found with url https://localhost:4430/publication-726d9842ec80bb127d60ea99049c45a6/OPS/c01.xhtml',
        details: [Object] },
     headers: {} },
  reformat: [Function],
  typeof: [Function: notFound] }
```

The format of the inReplyTo URL doesn't seem to matter as it also fails if I send `/publication-726d9842ec80bb127d60ea99049c45a6/OPS/c01.xhtml'`

_However_... if inReplyTo is `https://localhost:4430/publication-726d9842ec80bb127d60ea99049c45a6OPS/c01.xhtml` Then it _does_ work :-)

**Comment by baldurbjarnason** [comment]
The notes endpoint has the same kind of error:

- `https://localhost:4430/reader-951fc8baffbe41bbd39da234b376b919/notes?document=https%3A%2F%2Flocalhost%3A4430%2Fpublication-726d9842ec80bb127d60ea99049c45a6OPS%2Fc01.xhtml` works and returns the previously created note (`document = https://localhost:4430/publication-726d9842ec80bb127d60ea99049c45a6OPS/c01.xhtml`)
- `https://localhost:4430/reader-951fc8baffbe41bbd39da234b376b919/notes?document=https%3A%2F%2Flocalhost%3A4430%2Fpublication-726d9842ec80bb127d60ea99049c45a6%2FOPS%2Fc01.xhtml` does not (`document = https://localhost:4430/publication-726d9842ec80bb127d60ea99049c45a6/OPS/c01.xhtml`)

**Comment by Marie000** [comment]
When your document was created in the publication file upload endpoint, what was its path?
