### ISSUE TITLE
Endpoint naming

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#427]
There are still a few endpoints I am not sure about:

- Create read activity
`POST /read-activities` or `POST publications/:pubId/read-activities` or `POST readers/:readerId/read-activities`

- Get tags
`GET /tags` or `GET /readers/:id/tags`
we do not strictly need the readerId there. I can get it from the token, but since we are getting the tags for a particular user, would it make sense in this case to leave the readers/:id part?

- Get library
Similarly, we could use `GET /readers/:id/library`
I use library here instead of publications because strictly speaking we are not returning a list of publications. We are returning the reader object with a list of publications, a list of tags... 

- Get notes
Not sure what to name this one. I have it currently listed as `GET /readers/:id/notes` but once again, we are not really getting a list of notes. So maybe something like `GET /readers/:id/notes-collection` ?

**Comment by baldurbjarnason** [comment]
Oooh, good questions.

My 2 cents:

- Given that we're (probably) going to surface read activities a bit more in the UI, it probably makes sense to use the URL to create a stronger association between the activity and the pub? So `POST publications/:pubId/read-activities`?
- I know this might be weird but I really like the consistency of having `POST /publications` create an item and `GET /publications` getting a list of items even if that list comes with other things as well.
- Which in turn means that I'd prefer `/tags` and `/notes` as well.

This is just a preference, mind you.
