### ISSUE TITLE
`/whoami` and `/readers` endpoints are unnecessarily opinionated about the userId

### ISSUE THREAD

**Issue by baldurbjarnason** [RebusFoundation/reader-api#48]
## Description:

All of the user ids we get from Auth0 take the following form:

`service_identifier|service_specific_UUID`

The prefix is there because Auth0 doesn't know how each service generates its UUID and so can't guarantee uniqueness without a service-specific prefix.

Currently API server expects the user id coming from Auth0 to not include the service identifying prefix and also expects it to always be `auth0`.

Example (from `routes/readers.js`):
```
Reader.query(Reader.knex())
      .where('userId', '=', `auth0|${userId}`)
```
From `models/Reader.js`:

```
  static async byUserId (userId, namespace = 'auth0') {
    const readers = await Reader.query(Reader.knex()).where(
      'userId',
      '=',
      `${namespace}|${userId}`
    )
// ... Rest of function omitted
}
```

## Problem

This namespacing in the code is unnecessary as the front-end should treat the user id it gets from Auth0 as an opaque id and should not attempt to separate the prefix from the rest of the id.

This problem should not actually break anything but it means that every user id in the database ends up double-prefixed.

**Comment by Marie000** [comment]
No longer relevant.
