### ISSUE TITLE
Test that publications are added to the reader's library

### ISSUE THREAD

**Issue by evanp** [RebusFoundation/reader-api#53]
The mainline-api test suite tests create a new publication, and check that the publication and corresponding documents are created. It doesn't test that the publication is added to the library. This is probably a good thing to test, since it's the main way a client can discover what publications a reader has.

**Comment by Marie000** [comment]
note: add this to integration tests.

**Comment by Marie000** [comment]
On second look, I already did test that in my integration tests.
