### ISSUE TITLE
`Document.asRef` strips out properties that the frontend requires

### ISSUE THREAD

**Issue by baldurbjarnason** [RebusFoundation/reader-api#58]
JSON serialisation of Documents when embedded in the Publication JSON strips out all properties except name, type and id. This strips out properties specific to epubs that the front end needs to be able to decide which document matches a relative link or media embed in another document, breaking all links, images and, in same cases, reading order.

There are a few ways to fix this but the simplest would be to instead strip out specific blackisted bandwidth-heavy properties instead of whitelisting allowed properties. My suggestion would be to strip out the `content` and `contentMap` properties to begin with and keep the rest.

**Comment by Marie000** [comment]
I am still confused as to what asRef should keep and what it should remove. For both the publication and the document.

**Comment by Marie000** [comment]
Makes sense. 
I will leave that aside then. If, after changing the way we handle the content, we find we still need the asRef, I will reconsider. If not, I will close the issue then.
