### ISSUE TITLE
Publication#asRef breaks everything (was: completely mangles author attributions)

### ISSUE THREAD

**Issue by baldurbjarnason** [RebusFoundation/reader-api#79]
Publication#asRef at the moment completely misunderstands how publication authorship and attributions work (it assumes that each publication only has one author).

One way of resolving this would be to defer to the JSON serialisation logic built into the Model Class (e.g. use `#toJSON` which in turn calls `#formatJson`) and then strip out the properties you don't want, or just pick the properties to keep. Either way, I think it makes sense for us to try to avoid multiple implementations of the JSON serialisation logic for the various properties and instead try to reuse `#toJSON` where we can.

**Comment by Marie000** [comment]
There is something strange going on and I have no idea why.

Document.asRef() returns: `_.omit(this.toJSON(), ['content', 'contentMap'])`
which is: 
```
{ type: 'Document',
  name: 'Chapter 1',
  position: 0,
  context: undefined,
  id: 'https://reader-api.test/document-stPyLqiAbRqnKusaCuAKVU',
  published: '2019-01-11T16:32:25.926Z',
  updated: '2018-12-18 15:54:12',
  attachment: undefined,
  attributedTo: [] }
```

I did something similar for Publication.asRef(): `_.omit(this.toJSON(), 'attachment')`
and the result is:
```
{ id: 'https://reader-api.test/publication-9KmTSFLDQJLR2WEzhsmLTE',
  description: null,
  json:
   { type: 'reader:Publication',
     name: 'Publication A',
     attributedTo: [ { type: 'Person', name: 'Sample Author' } ] },
  summaryMap:
   { en: 'object with id 46d6f7cf-5727-46ba-9a57-93bb8f1997e4' },
  context: undefined,
  published: '2019-01-11T16:32:26.906Z',
  updated: '2019-01-11 16:32:26',
  attributedTo: [],
  orderedItems: [] }
```

Trying to figure out why the structure is completely different. :confused:

**Comment by baldurbjarnason** [comment]
That is really weird.

It looks like in the latter case the internal `$formatJson` method is not being called by `toJSON()` as it should. 😐

**Comment by baldurbjarnason** [comment]
So, having another look at this as a part of the library work it turns out that I've been so focused on the reading UI that I'd completely forgotten that `Publication#asRef()` is still pretty broken.

The two biggest omissions:

- Attributions are broken as it assumes that `attributedTo` is an object with a single author when it's an array of creators
- Covers (the `Publication#icon` property) are not included.

Again, as with `Document#asRef` I think we've moved beyond the need to omit properties. As long as the Publication isn't eagerly loading any relations returning the entire Publication object in listings such as the library should not be a problem.

**Comment by Marie000** [comment]
Publication has changed completely and I don't think any of those problems stil lapply. So I will close this issue. If we have more problems with asRef, we can open a new issue later.
