### ISSUE TITLE
Improve file upload

### ISSUE THREAD

**Issue by Marie000** [RebusFoundation/reader-api#96]

**Comment by baldurbjarnason** [comment]
A few things we need from file uploads:

- Each file upload needs to be put in a user-specific directory in Google Storage. The user's id should work.
- It needs to have a simple mechanism for access control. The simplest way to do this is to upload each file to an unguessable URL (i.e. use `crypto.randomBytes` to create a secure unguessable token that's used as the actual filename in storage).
- We need to be able to upload multiple text files in a single request. Ebooks are generally composed of many very small text-based files (html, xml, css, etc.) and uploading them one at a time can. take. a. long. time. If I could upload the text files all at once that would make book imports much quicker.
- We _don't_ need to be able to upload more than one binary (e.g. media, images, etc.) at a time. At least, not at this point.

At some point we also need to be able to delete uploaded files. But that's probably a separate issue and further down the line.

**Comment by Marie000** [comment]
I was thinking that the response for this route would be some sort of map with the old filename pointing to the url of the file. So something like:
```
{
  "filename1.html": "/{readerShortId}/{randomName}.html",
  "filename2.html": "/{readerShortId}/{randomName}.html"
}
```
Does that make sense?

**Comment by baldurbjarnason** [comment]
👍 Yup, that makes sense.
